Update README.md
watson-developer-cloud/dotnet-standard-sdk pull request #471
Opened 2021-07-26 14:32 UTC by mediumTaj

### Summary

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here.

Thanks for contributing to the Watson Developer Cloud!

2021-07-28 14:55 UTC, kevinkowa approved these changes
LGTM!

2021-07-28 19:59 UTC, SirSpidey requested changes
Changes here are correct, but don't catch the link at line 38 or so. Goes to different place than others. Probably should either use the link definition at the bottom or get rid of those if they're not used.

2021-07-28 19:59 UTC, SirSpidey commented on README.md
> +[discovery]: https://www.ibm.com/cloud/watson-discovery
This link definition is never used. And the link that is used is wrong at line 38

2021-07-29 17:45 UTC, mediumTaj commented
Updated and waiting for CI - @SirSpidey can you take a look again to make sure i caught everything?

2021-07-29 20:01 UTC, SirSpidey requested changes
some links not correct. Also deprecated services don't have product marketing pages.

2021-07-29 20:01 UTC, SirSpidey commented on README.md
>  * [Compare Comply](https://www.ibm.com/cloud/compare-and-comply)
```suggestion
* Compare Comply (deprecated)
```

2021-07-29 20:53 UTC, SirSpidey commented
@mediumTaj Just noticed that the Swift SDK has a treatment for the deprecated services that you might just duplicate here.

2021-07-30 15:31 UTC, SirSpidey approved these changes
👍

2021-07-30 16:54 UTC, merged